<?php

namespace Unit;


use DPRMC\GLMXFixClient\GLMXFixClient;
use PHPUnit\Framework\TestCase;

class MiscTest extends TestCase {


    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub


    }


    /**
     * @test
     */
    public function testShouldGenerateCashReport() {
        $client = new GLMXFixClient( $_ENV[ 'senderCompID' ], $_ENV[ 'password' ] );
        $this->assertInstanceOf( GLMXFixClient::class, $client);

        $client->connect();

        $client->disconnect();
    }


}